function createfigure3droptau(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 31-Jan-2010 20:32:44

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1,'Marker','.');
set(plot1(1),'DisplayName','drop1');
set(plot1(2),'DisplayName','drop2');
set(plot1(3),'DisplayName','drop3');

% Create xlabel
xlabel({'Number of oscillation'});

% Create ylabel
ylabel({'Period/2 (sec.)'});

% Create legend
legend(axes1,'show');

