function createfigure3droppsi(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 31-Jan-2010 20:27:28

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','drop2-drop1');
set(plot1(2),'DisplayName','drop3-drop2');
set(plot1(3),'DisplayName','drop1-drop3');

% Create xlabel
xlabel({'Time/2 (sec.)'});

% Create ylabel
ylabel({'Phase shift (0.5=pi)'});

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.781467013888893 0.82465531224655 0.122395833333333 0.0993511759935118]);

