function createfigure(X1, Y1, X2, Y2, X3, Y3)
%CREATEFIGURE(X1,Y1,X2,Y2,X3,Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 04-Feb-2010 16:45:11

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',12);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'Marker','o','DisplayName','drop1');

% Create plot
plot(X2,Y2,'Parent',axes1,'Marker','square','DisplayName','drop2');

% Create plot
plot(X3,Y3,'Parent',axes1,'Marker','x','DisplayName','drop3');

% Create xlabel
xlabel({'Time/2 (sec.)'},'FontSize',12);

% Create ylabel
ylabel({'Period/2 (sec.)'},'FontSize',12);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.70763888888889 0.464366213841579 0.0934895833333333 0.116869424168694]);

